site_name: Charlie Reporting Docs
site_url: https://example.local/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
nav:
  - Home: docs/index.md
  - Quickstart:
      - E2E Quickstart: docs/e2e-quickstart.md
      - Operations: docs/OPERATIONS.md
  - Architecture:
      - System Overview: docs/architecture/diagrams/system-overview.md
      - Common Service Architecture: docs/architecture/common_service_architecture.md
      - Project Structure: docs/architecture/project_structure.md
      - TDD-Optimized Architecture: docs/architecture/tdd-optimized-architecture.md
      - Components:
          - Scheduler: docs/architecture/diagrams/scheduler.md
          - Report Service: docs/architecture/diagrams/report-service.md
          - Simulator: docs/architecture/diagrams/component-simulator.md
          - API: docs/architecture/diagrams/component-api.md
          - Collector: docs/architecture/diagrams/component-collector.md
          - Loader: docs/architecture/diagrams/component-loader.md
          - Aggregator: docs/architecture/diagrams/component-aggregator.md
          - Excel/HTML: docs/architecture/diagrams/component-excel.md
          - Service Boundaries: docs/architecture/diagrams/service-boundaries.md
          - UML:
              - Ingest Sequence: docs/architecture/diagrams/uml/sequence-ingest.md
              - Generate Hourly: docs/architecture/diagrams/uml/sequence-generate-hourly.md
              - Simulator Generate: docs/architecture/diagrams/uml/sequence-simulator-generate.md
              - Class (Foundation): docs/architecture/diagrams/uml/class-foundation.md
  - APIs:
      - API Overview: docs/api_overview.md
      - Simulator Spec: docs/sharepoint_csv_sim_spec.md
      - Simulator Usage: docs/sharepoint_sim_usage.md
      - Simulator OpenAPI: docs/sharepoint_sim_openapi.json
  - Implementation:
      - Foundation Overview: docs/foundation-overview.md
      - Integration & Scheduler Spec: docs/integration_pipeline_todo_and_scheduler_spec.md
      - Testing Approach: docs/testing-approach.md
  - Delivery & Reports:
      - Final Status Report: docs/final-status-report.md
      - Phase 2 Summary: docs/phase2-summary.md
      - Migration Plan: docs/migration-plan.md
      - Deliverables: docs/deliverables/
  - Sprint & Process:
      - Sprint Reviews: docs/sprint-reviews/
      - Development Workflow: docs/development-workflow.md
      - Development Principles: docs/development_principles.md
      - Development Diary: docs/development-diary.md
  - Cleanups & Notes:
      - Cleanup Status: docs/cleanup-status-report.md
      - Report Generator Cleanup: docs/report-generator_cleanup.md
      - Test Migration Complete: docs/test-migration-complete.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true