[service]
host = "0.0.0.0"
port = 8083
debug = false
log_level = "INFO"

[processing]
max_file_size_mb = 100
max_files_per_request = 50
processing_timeout_seconds = 300
enable_file_archival = true

[csv]
csv_encoding = "utf-8"
csv_delimiter = ","
csv_quote_char = '"'
max_csv_rows = 1000000

[excel]
excel_engine = "openpyxl"
max_sheets_per_workbook = 255
excel_date_format = "YYYY-MM-DD"
excel_datetime_format = "YYYY-MM-DD HH:MM:SS"

[monitoring]
enable_metrics = true
metrics_retention_hours = 24
health_check_interval_seconds = 30
