[service]
name = "scheduler-service"
host = "localhost"
port = 8082
debug = true
environment = "local"

[logging]
level = "DEBUG"
file = "logs/scheduler-service-local.log"
json_format = true

[metrics]
enabled = true
port = 9092

[health]
check_interval = 30.0
