global_email_filter:
  sender: ["reports@example.com"]
  subject_contains: ["Daily Report"]

attachments:
  IB Calls.csv:
    range: G:I

  QCBs.csv:
    range: G:H

  Dials.csv:
    range: G:K

  Prod.csv:
    range: F:K

  Campaign.csv:
    range: E:H

  ACQ.csv:
    range: G:H

  RESC.csv:
    range: G:H
