[service]
name = "email-service"
host = "localhost"
port = 8084
debug = true
environment = "local"

[logging]
level = "DEBUG"
file = "logs/email-service-local.log"
json_format = true

[metrics]
enabled = true
port = 9094

[health]
check_interval = 30.0
