[general]
debug = true
log_level = "INFO"
date_format = "%Y-%m-%d"

[email]
outlook_folder = "Inbox/Genesys"
outlook_account = "jontajon191@gmail.com"  # Your secondary email
sender = ["genesysreports@genesysdev.com"]
subject_contains = ["Hourly Report", "Call Center Data"]

[directory_scan]
enabled = false
scan_path = "demo/data/raw"  # Demo data directory
process_subdirs = false

[attachments]
"IB_Calls.csv"              = ["Agent Name", "Handle", "Avg Handle"]
"QCBs.csv"                  = ["Agent Name", "Handle"]
"Dials.csv"                 = ["Agent Name", "Handle", "Avg Handle", "Avg Talk", "Avg Hold"]
"Productivity.csv"          = ["Agent Name", "Logged In", "On Queue", "Idle", "Off Queue", "Interacting"]
"Campaign_Interactions.csv" = ["Date", "Initial Direction", "First Queue"]
"ACQ.csv"                   = ["Agent Name", "Handle"]
"RESC.csv"                  = ["Agent Name", "Handle"]

[output]
excel_dir = "demo/data/output"
archive_dir = "demo/data/archive"
excel_prefix = "demo_report_"

[directories]
data_dir = "demo/data"
logs_dir = "demo/logs"
archive_dir = "demo/data/archive"

[processing]
mode = "interval"  # Support for sub-hourly processing
enable_summaries = true
archive_after_processing = true
