name: ci
on: [push, pull_request]
jobs:
  style-and-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff mypy pydantic
          python -m pip install -e .[dev]
      - name: Ruff (lint)
        run: ruff check src foundation/src
      - name: Ruff (format check)
        run: ruff format --check src foundation/src
      - name: mypy (strict)
        run: mypy src foundation/src
