[general]
debug = true
log_level = "INFO"
date_format = "%Y-%m-%d"

[email]
outlook_folder = "Inbox"
outlook_account = "jontajon191@gmail.com"  # Your secondary email
sender = ["charlie.reporting.dev@gmail.com"]
subject_contains = ["Test CSV Attachment", "Hourly Report", "Call Center Data"]

# SMTP Configuration for sending demo emails
[smtp]
server = "smtp.gmail.com"
port = 587
sender_email = "jwardwell7077@gmail.com"  # Can be overridden by GMAIL_ADDRESS env var
sender_name = "Genesys Call Center Reports"  # Display name for emails
target_email = "jontajon191@gmail.com"  # Can be overridden by TARGET_EMAIL env var

# Authentication method: "env_vars", "oauth", or "app_password"
auth_method = "env_vars"
credentials_file = "credentials.json"  # For OAuth or service account
token_file = "token.json"  # For OAuth token storage

[directory_scan]
enabled = false
scan_path = "demo/data/raw"  # Demo data directory
process_subdirs = false

[attachments]
"IB_Calls.csv"              = ["Agent Name", "Handle", "Avg Handle"]
"QCBs.csv"                  = ["Agent Name", "Handle"]
"Dials.csv"                 = ["Agent Name", "Handle", "Avg Handle", "Avg Talk", "Avg Hold"]
"Productivity.csv"          = ["Agent Name", "Logged In", "On Queue", "Idle", "Off Queue", "Interacting"]
"Campaign_Interactions.csv" = ["Date", "Initial Direction", "First Queue"]
"ACQ.csv"                   = ["Agent Name", "Handle"]
"RESC.csv"                  = ["Agent Name", "Handle"]

[output]
excel_dir = "demo/data/output"
archive_dir = "demo/data/archive"
excel_prefix = "demo_report_"

[directories]
data_dir = "demo/data"
logs_dir = "demo/logs"
archive_dir = "demo/data/archive"

[processing]
mode = "interval"  # Support for sub-hourly processing
enable_summaries = true
archive_after_processing = true
